SELECT YEAR(YM) AS YEAR, -- DATE_FORMAT(YM, '%Y')보다 간결합니다.
       ROUND(AVG(PM_VAL1), 2) AS 'PM10', 
       ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원'
GROUP BY YEAR 
ORDER BY YEAR ASC;